### 1. Perform Login
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=martina&password=test123


### 2. Get following
GET http://localhost:8080/api/users/followers/koco