### 1. Perform Login
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=martina&password=test123

### 2. Save a Tweet
POST http://localhost:8080/api/tweets
Content-Type: application/json

{
  "username": "martina",
  "content": "Tweet DTO test tweet",
  "imageUrl": null,
  "parentId": null
}

### 3. Get tweets
GET http://localhost:8080/api/tweets?username=koco
Content-Type: application/json